This script is to add BEAST results (generated independently of the nextflow workflow) to the figures.

```{r}
library(tidyverse)
library(treeio)
```

Load BEAST data
```{r}
data_dir <- "clean_results/confa_sensitivity/results_replicate_1"
beast_treeio <- treeio::read.beast(paste0(data_dir, "/beast/mcc.tree"))
location_col <- 18
location_colname <- "region"
outbreak_annotation <- "CONF_A"

# data_dir <- "clean_results/urmc/results_2023-05-15T13:15:38.785201-07:00"
# beast_treeio <- treeio::read.beast(paste0(data_dir, "/beast/combined_chains_mcc.tree"))
# location_col <- 14
# location_colname <- "location"
# outbreak_annotation <- "URMC"
```

Collate per-sample results
```{r}
node_annotations <- as.data.frame(as_tibble(beast_treeio))
beast_phylo <- ape::as.phylo(beast_treeio)

# pre-order tree traversal to find outbreak MRCA nodes
beast_phylo <- ape::reorder.phylo(beast_phylo, order = "postorder", index.only = F)
postorder_edges <- beast_phylo$edge

# Traverse tree, finding import events
is_first <- T
for (i in nrow(postorder_edges):1) {
    parent <- postorder_edges[i, 1]
    child <- postorder_edges[i, 2]
    parent_annotation <- node_annotations[parent, location_colname]
    child_annotation <- node_annotations[child, location_colname]
    print(paste("parent:", parent_annotation, "& child:", child_annotation))
    if (parent == child || child_annotation != parent_annotation) {
        introduction_data_tmp <- data.frame(
            parent = parent,
            child = child,
            parent_annotation = parent_annotation,
            child_annotation = child_annotation
        )
        if (is_first) {
            introduction_data <- introduction_data_tmp
            is_first <- F
        } else {
            introduction_data <- rbind(introduction_data, introduction_data_tmp)
        }
    }  
}
```

Get beast imports in a per-sample tabular format
```{r}
root_idx <- postorder_edges[nrow(postorder_edges), 1]

# function to see if a node is the child of an introduction
get_introduction <- function(node_idx, introduction_data) {
    print(paste("investigating node", node_idx))
    if (node_idx %in% introduction_data$child) {
        return(node_idx)
    } else if (node_idx == root_idx) {
        # special case at root: it has to be an introduction
        return(node_idx)
    } else {
        parent <- postorder_edges[which(postorder_edges[, 2] == node_idx), 1]
        return(get_introduction(parent, introduction_data))
    }
}

n_tips <- length(beast_phylo$tip.label)
is_first <- T
for (i in 1:n_tips) {
    sample_data_tmp <- data.frame(
        sample = beast_phylo$tip.label[i],
        region = node_annotations[i, location_col],
        introduction_node = get_introduction(i, introduction_data))
    if (is_first) {
        sample_data <- sample_data_tmp
        is_first <- F
    } else {
        sample_data <- rbind(sample_data, sample_data_tmp)
    }
}

beast_results <- sample_data %>%
    group_by(introduction_node) %>%
    mutate(cluster_size = n()) %>%
    mutate(method = "beast")
```

Write out per-sample results
```{r}
previous_results <- read.table(
    paste0(data_dir, "/collated_results_per_sample.txt"),
    header = T)

write.table(
    x = rbind(previous_results, beast_results), 
    file = paste0(data_dir, "/collated_results_per_sample_with_beast.txt"),
    row.names = F)
```

Collate results per introduction
```{r}
# function to see if a node is the child of an outbreak introduction
get_outbreak_introduction <- function(node_idx, root_idx, outbreak_introductions) {
    if (node_idx %in% outbreak_introductions$child) {
        # base case - reached outbreak introduction
        return(node_idx)
    } else if (node_idx == root_idx) {
        # base case - reached root and no outbreak introduction found
        return(NA)
    } else {
        parent <- postorder_edges[which(postorder_edges[, 2] == node_idx), 1]
        return(get_outbreak_introduction(parent, root_idx, outbreak_introductions))
    }
}

outbreak_introductions <- introduction_data %>% filter(child_annotation == outbreak_annotation)
n_tips <- length(beast_phylo$tip.label)
is_first <- T
for (i in 1:n_tips) {
    descendent_data_tmp <- data.frame(
        tip = i,
        label = beast_phylo$tip.label[i],
        tip_location = node_annotations[i, location_colname],
        introduction_node = get_outbreak_introduction(i, n_tips + 1, outbreak_introductions))
    if (is_first) {
        descendent_data <- descendent_data_tmp
        is_first <- F
    } else {
        descendent_data <- rbind(descendent_data, descendent_data_tmp)
    }
}

beast_descendent_data <- descendent_data %>%
    filter(!is.na(introduction_node)) %>%
    mutate(method = "beast")
```

Write out per-introduction results
```{r}
previous_results <- read.table(
    paste0(data_dir, "/collated_results_per_introduction.txt"),
    header = T)

write.table(
    x = rbind(previous_results, beast_descendent_data), 
    file = paste0(data_dir, "/collated_results_per_introduction_with_beast.txt"),
    row.names = F)
```