This script is to collate output files from different methods into a unified results files

```{r}
library(tidyverse)
library(treeio)
library(rjson)

# Analysis-specific parameters
outbreak_annotation <- "CONF_A"
data_dir <- "nextflow/results/boston_confa"
full_metadata <- read.delim(paste0(data_dir, "/metadata_with_context.tsv"))
outbreak_metadata <- full_metadata %>% filter(division == outbreak_annotation)
```

# Load tabular results files
```{r}
clustertracker_results <- read.delim(paste0(data_dir, "/clustertracker/introductions.tsv"))
```

# Deal with tree results files
Convert timetree output to New Hampshire eXtended format
```{bash}
cd nextflow/results/boston_confa/mugration/
grep "^ Tree" annotated_tree.nexus | sed "s/ Tree tree1=//g" | sed "s/&/&&NHX:/g" > annotated_tree.nhx
cd ../../../../
```

Get clusters from treetime mugration output
```{r}
mugration_treeio <- treeio::read.nhx(paste0(data_dir, "/mugration/annotated_tree.nhx"))
node_annotations <- as.data.frame(as_tibble(mugration_treeio))
mugration_phylo <- ape::as.phylo(mugration_treeio)

# pre-order tree traversal to find outbreak MRCA nodes
mugration_phylo <- ape::reorder.phylo(mugration_phylo, order = "postorder", index.only = F)
postorder_edges <- mugration_phylo$edge

# Traverse tree, finding import events
is_first <- T
for (i in nrow(postorder_edges):1) {
    parent <- postorder_edges[i, 1]
    child <- postorder_edges[i, 2]
    parent_annotation <- node_annotations[parent, 5]
    child_annotation <- node_annotations[child, 5]
    if (is.na(parent_annotation) || child_annotation != parent_annotation) {
        introduction_data_tmp <- data.frame(
            parent = parent,
            child = child,
            parent_annotation = parent_annotation,
            child_annotation = child_annotation
        )
        if (is_first) {
            introduction_data <- introduction_data_tmp
            is_first <- F
        } else {
            introduction_data <- rbind(introduction_data, introduction_data_tmp)
        }
    }  
}
```

Get mugration imports in a per-sample tabular format
```{r}
# function to see if a node is the child of an introduction
get_introduction <- function(node_idx, introduction_data) {
    if (node_idx %in% introduction_data$child) {
        return(node_idx)
    } else {
        parent <- postorder_edges[which(postorder_edges[, 2] == node_idx), 1]
        return(get_introduction(parent, introduction_data))
    }
}

n_tips <- length(mugration_phylo$tip.label)
is_first <- T
for (i in 1:n_tips) {
    sample_data_tmp <- data.frame(
        sample = mugration_phylo$tip.label[i],
        region = node_annotations[i, 5],
        introduction_node = get_introduction(i, introduction_data))
    if (is_first) {
        sample_data <- sample_data_tmp
        is_first <- F
    } else {
        sample_data <- rbind(sample_data, sample_data_tmp)
    }
}

mugration_results <- sample_data %>%
    group_by(introduction_node) %>%
    mutate(cluster_size = n())
```

Parse HIV-TRACE json output
```{r}
clusters_json <- readr::read_file(paste0(data_dir, "/hiv_trace/clusters.json"))
clusters_list <- rjson::fromJSON(json_str = clusters_json)

cluster_idxs <- clusters_list$trace_results$Nodes$cluster$values
clustered_sample_names <- clusters_list$trace_results$Nodes$id

cluster_results <- data.frame(
    sample = clustered_sample_names,
    introduction_node = cluster_idxs)

outbreak_sample_names <- outbreak_metadata$strain
sample_names <- full_metadata$strain
n_clusters <- clusters_list$trace_results$`Network Summary`$Clusters
n_singletons <- clusters_list$trace_results$`Network Summary`$Singletons

singleton_results <- data.frame(
    sample = sample_names[!(sample_names %in% clustered_sample_names)],
    introduction_node = n_clusters:(n_clusters + n_singletons - 1))  # hivtrace clusters are zero-indexed

hivtrace_results <- rbind(cluster_results, singleton_results) %>% 
    group_by(introduction_node) %>% 
    mutate(cluster_size = n()) %>%
    mutate(region = case_when(
        sample %in% outbreak_sample_names ~ outbreak_annotation, T ~ "Other"))
```

# Combine all results
```{r}
full_results <- rbind(
    clustertracker_results %>% 
        select(sample, introduction_node, cluster_size, region) %>%
        mutate(method = "clustertracker"),
    mugration_results %>% mutate(method = "mugration"),
    hivtrace_results %>% mutate(method = "hivtrace")
)

# TODO: parse mugration results to be per-sample for all samples, not just those under cluster introduction nodes
full_results %>%
    group_by(method) %>%
    summarize(n_samples = n())

# inspect results
full_results %>%
    group_by(method, introduction_node) %>%
    summarize(
        n_outbreak_samples = sum(region == outbreak_annotation),
        n_total_samples = n()) %>%
    arrange(desc(n_outbreak_samples))

# save results
write.table(
    x = full_results, 
    file = paste0(data_dir, "/collated_results.txt"),
    row.names = F)
```