name: Test NF workflows

on:
  push:
    branches:
      - main
      - traverse-mat
  workflow_dispatch:

jobs:
  test-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Load cache
        uses: actions/cache@v3
        with:
          key: nextflow-cache
          path: /opt/hostedtoolcache/nextflow

      - name: Set up nextflow
        uses: nf-core/setup-nextflow@v1.2.0

      - name: Run workflow 
        run: |
          cd ${{ github.workspace }}/nextflow/wf_bacteria
          ./run_wf_test.sh

      # - name: Cache Docker layers
      #   uses: actions/cache@v3
      #   with:
      #     path: /tmp/.buildx-cache
      #     key: ${{ runner.os }}-buildx-${{ inputs.cache }}-${{ github.sha }}
      #     restore-keys: |
      #       ${{ runner.os }}-buildx-${{ inputs.cache }}

      #   # Temp fix
      #   # https://github.com/docker/build-push-action/issues/252
      #   # https://github.com/moby/buildkit/issues/1896
      # - name: Move cache
      #   run: |
      #     rm -rf /tmp/.buildx-cache
      #     mv /tmp/.buildx-cache-new /tmp/.buildx-cache

